### ISSUE TITLE
Integrate API Testing

### ISSUE THREAD

**Issue by sarahswinton** [iwishiwasaneagle/boxofhope#63]
Create a workflow for GitHub actions/CI.

**Comment by iwishiwasaneagle** [comment]
I would recommend using a [MongoDB docker container][1] to simplify the setup, and [Docker layer caching][2] to speed up the run times of the Github Actions.

[1]: https://hub.docker.com/_/mongo
[2]: https://github.com/marketplace/actions/docker-layer-caching
