### ISSUE TITLE
API CI is failing but since "npm start" is run as a thread, it doesn't fail the tests.

### ISSUE THREAD

**Issue by iwishiwasaneagle** [iwishiwasaneagle/boxofhope#68]
https://github.com/iwishiwasaneagle/boxofhope/blob/bb7c25c6ef2580a9712ebcac93b5e3cebd0d7bf4/.github/workflows/api_ci.yml#L41

https://github.com/iwishiwasaneagle/boxofhope/runs/2042732040?check_suite_focus=true#step:6:106

![image](https://user-images.githubusercontent.com/12383029/110248648-1b869d80-7f6a-11eb-8966-979beff26069.png)

**Comment by sarahswinton** [comment]
Issue resolved with updated Postman tests.
