### ISSUE TITLE
Endpoints using `findOneAndUpdate` don't find anything on fresh mongoDB

### ISSUE THREAD

**Issue by iwishiwasaneagle** [iwishiwasaneagle/boxofhope#69]
https://github.com/iwishiwasaneagle/boxofhope/blob/bb7c25c6ef2580a9712ebcac93b5e3cebd0d7bf4/api/controllers/stateController.js#L71-L78

Mongoose doesn't find anything and therefore the logic inside the callback is skipped. The following shows that the `res.status(200)` is called.

![image](https://user-images.githubusercontent.com/12383029/110248750-96e84f00-7f6a-11eb-9c16-f10c9915fa6a.png)

## Recommended fix
Don't update one entry, but rather create a new one for each request. This allows the webapp to display interesting data down the line.

**Comment by sarahswinton** [comment]
Resolved status codes, errors now specifically return 404 code.
Testing to cover mask related requests complete. Further testing coming later today.
I'll set up user_home to create a new entry per request.
